default_platform(:ios)

platform :ios do

  lane :fetch_profile do
    api_key = app_store_connect_api_key(
      key_id:       ENV["ASC_KEY_ID"],
      issuer_id:    ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["P8_PATH"],
      duration:     1200,
      in_house:     false
    )

    sigh(
      api_key:           api_key,
      app_identifier:    ENV["IOS_BUNDLE_ID"],
      team_id:           ENV["IOS_TEAM_ID"],
      provisioning_name: "B4A_#{ENV['IOS_BUNDLE_ID']}_APPSTORE",
      readonly:          false,
      output_path:       "#{ENV['HOME']}/Library/MobileDevice/Provisioning Profiles"
    )
  end

  lane :ensure_app do
    api_key = app_store_connect_api_key(
      key_id:       ENV["ASC_KEY_ID"],
      issuer_id:    ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["P8_PATH"],
      duration:     1200,
      in_house:     false
    )

    produce(
      api_key:        api_key,
      app_identifier: ENV["IOS_BUNDLE_ID"],
      team_id:        ENV["IOS_TEAM_ID"],
      app_name:       ENV["APP_NAME"],
      sku:            ENV["IOS_BUNDLE_ID"],
      skip_itc:       false
    )
  end

  lane :upload_testflight do
    api_key = app_store_connect_api_key(
      key_id:       ENV["ASC_KEY_ID"],
      issuer_id:    ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["P8_PATH"],
      duration:     1200,
      in_house:     false
    )

    pilot(
      api_key:                          api_key,
      ipa:                              ENV["IPA_PATH"],
      app_identifier:                   ENV["IOS_BUNDLE_ID"],
      skip_waiting_for_build_processing: true,
      distribute_external:              false,
      skip_submission:                  true,
      changelog:                        "Gym CI build"
    )
  end

end